### ISSUE TITLE
Hide symbols that are not meant ot be public

### ISSUE THREAD

**Issue by mattip** [MacPython/openblas-libs#79]
Over at numpy/numpy#21643 it turns out that when we use `SYMBOLSUFFIX` not all the exported symbols are converted. For instance, in NumPy 1.22.4, we have `cblas_dgemm64_` calling `dgemm_nn` which does not have the `64_` suffix:
```
$ objdump /tmp/venv/lib/python3.10/site-packages/numpy.libs/libopenblas64_p-r0-2f7c42d4.3.18.so -T | grep dgemm_nn
00000000001fdb40 g    DF .text	0000000000000638  Base        dgemm_nn
```

This is problematic if there is a different openblas.so already loaded into the process. The first one's symbols (which could be using a 32-bit interface) will be used, which can segfault.

Should we be adding `CFLAGS=-fvisibility=hidden to [our builds](https://github.com/MacPython/openblas-libs/blob/cc761826c220cb2c44b82d8dee4c11c3db44cae6/travis-ci/build_steps.sh#L166)?

@martin-frbg thoughts?

**Comment by mattip** [comment]
I seem to recall that on windows there is a concept of dll namespaces so this will not happen.

**Comment by martin-frbg** [comment]
I guess until now everybody involved with this SYMBOLSUFFIX thing had assumed that "internal" symbols would be resolved within the same library. The suffixing itself is done as a post-processing step (by the exports/gensymbol script) IIRC so it may be possible to transform these internal symbols as well. (Not sure if enforcing "hidden" via CFLAGS would work without decorating all the non-internal functions with a `visibility("default")` attribute ? Also not sure how portable the `__attribute__` is)

**Comment by seberg** [comment]
Over in the NumPy issue, it seems to me like a better hot-fix will be `-fvisibility=protected`.  Since that should avoid having to mark all public functions as `"default"` visibility (although maybe that is still better).
(Since OpenBLAS does the name mangling, maybe adding the visibility `default` attribute is the cleaner long-term fix though?)

I agree with Matti, that I am unsure we need cross-platform support.  IIRC, windows does linking safer anyway and I suspect also OSX may be safer in this regard (but clang supports visibility anyway).
